# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fares/Documents/devel/pypointage2/view/authWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authWindow(object):
    def setupUi(self, authWindow):
        authWindow.setObjectName("authWindow")
        authWindow.resize(298, 183)
        authWindow.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(authWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appName = QtWidgets.QLabel(authWindow)
        self.appName.setStyleSheet("font: 14pt \"Noto Sans\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(195, 159, 91, 255), stop:1 rgba(255, 255, 255, 255));")
        self.appName.setAlignment(QtCore.Qt.AlignCenter)
        self.appName.setObjectName("appName")
        self.verticalLayout.addWidget(self.appName)
        self.label = QtWidgets.QLabel(authWindow)
        self.label.setStyleSheet("color: rgb(245, 10, 10);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pwdL = QtWidgets.QLabel(authWindow)
        self.pwdL.setObjectName("pwdL")
        self.gridLayout.addWidget(self.pwdL, 1, 0, 1, 1)
        self.UserL = QtWidgets.QLabel(authWindow)
        self.UserL.setObjectName("UserL")
        self.gridLayout.addWidget(self.UserL, 0, 0, 1, 1)
        self.lineEditUsr = QtWidgets.QLineEdit(authWindow)
        self.lineEditUsr.setObjectName("lineEditUsr")
        self.gridLayout.addWidget(self.lineEditUsr, 0, 1, 1, 1)
        self.lineEditPwd = QtWidgets.QLineEdit(authWindow)
        self.lineEditPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPwd.setObjectName("lineEditPwd")
        self.gridLayout.addWidget(self.lineEditPwd, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(71, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(authWindow)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(authWindow)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.pwdL.setBuddy(self.lineEditPwd)
        self.UserL.setBuddy(self.lineEditUsr)

        self.retranslateUi(authWindow)
        self.okButton.clicked.connect(authWindow.accept) # type: ignore
        self.cancelButton.clicked.connect(authWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(authWindow)
        authWindow.setTabOrder(self.lineEditUsr, self.lineEditPwd)
        authWindow.setTabOrder(self.lineEditPwd, self.okButton)
        authWindow.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, authWindow):
        _translate = QtCore.QCoreApplication.translate
        authWindow.setWindowTitle(_translate("authWindow", "Dialog"))
        self.appName.setText(_translate("authWindow", "GPT"))
        self.pwdL.setText(_translate("authWindow", "Password"))
        self.UserL.setText(_translate("authWindow", "User"))
        self.cancelButton.setText(_translate("authWindow", "&Cancel"))
        self.okButton.setText(_translate("authWindow", "&OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    authWindow = QtWidgets.QDialog()
    ui = Ui_authWindow()
    ui.setupUi(authWindow)
    authWindow.show()
    sys.exit(app.exec_())
