# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fares/Documents/devel/pypointage2/view/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("info")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.info)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.info)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.info, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuPersonnel = QtWidgets.QMenu(self.menuBar)
        self.menuPersonnel.setObjectName("menuPersonnel")
        self.menuConfiguration = QtWidgets.QMenu(self.menuBar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuCalcules = QtWidgets.QMenu(self.menuBar)
        self.menuCalcules.setObjectName("menuCalcules")
        self.menudebug_and_test = QtWidgets.QMenu(self.menuBar)
        self.menudebug_and_test.setObjectName("menudebug_and_test")
        MainWindow.setMenuBar(self.menuBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionListe_des_personnels = QtWidgets.QAction(MainWindow)
        self.actionListe_des_personnels.setObjectName("actionListe_des_personnels")
        self.actionListe_de_Pointage = QtWidgets.QAction(MainWindow)
        self.actionListe_de_Pointage.setObjectName("actionListe_de_Pointage")
        self.actionCalcule_Pointage = QtWidgets.QAction(MainWindow)
        self.actionCalcule_Pointage.setObjectName("actionCalcule_Pointage")
        self.actionListe_ptModel = QtWidgets.QAction(MainWindow)
        self.actionListe_ptModel.setObjectName("actionListe_ptModel")
        self.actionlecture_pointeuse = QtWidgets.QAction(MainWindow)
        self.actionlecture_pointeuse.setObjectName("actionlecture_pointeuse")
        self.actionPointage_Brute = QtWidgets.QAction(MainWindow)
        self.actionPointage_Brute.setObjectName("actionPointage_Brute")
        self.menuFile.addAction(self.actionQuit)
        self.menuPersonnel.addAction(self.actionlecture_pointeuse)
        self.menuPersonnel.addAction(self.actionPointage_Brute)
        self.menuPersonnel.addAction(self.actionListe_de_Pointage)
        self.menuPersonnel.addAction(self.actionListe_ptModel)
        self.menuCalcules.addAction(self.actionCalcule_Pointage)
        self.menudebug_and_test.addAction(self.actionListe_des_personnels)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuPersonnel.menuAction())
        self.menuBar.addAction(self.menuCalcules.menuAction())
        self.menuBar.addAction(self.menuConfiguration.menuAction())
        self.menuBar.addAction(self.menudebug_and_test.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10.5pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Utilisation</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Workflow</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">description des taches cotidiennes</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("MainWindow", "Info"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.info), _translate("MainWindow", "Manuel Utilisation GPT"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPersonnel.setTitle(_translate("MainWindow", "Personnel"))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration"))
        self.menuCalcules.setTitle(_translate("MainWindow", "Calcules"))
        self.menudebug_and_test.setTitle(_translate("MainWindow", "debug and test"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionListe_des_personnels.setText(_translate("MainWindow", "Liste des personnels"))
        self.actionListe_de_Pointage.setText(_translate("MainWindow", "Liste de Pointage"))
        self.actionCalcule_Pointage.setText(_translate("MainWindow", "Calcule Pointage"))
        self.actionListe_ptModel.setText(_translate("MainWindow", "Liste ptModel"))
        self.actionlecture_pointeuse.setText(_translate("MainWindow", "lecture pointeuse"))
        self.actionPointage_Brute.setText(_translate("MainWindow", "Pointage Brute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
