# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fares/Documents/devel/pypointage2/view/pagedTabelView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PagedTableView(object):
    def setupUi(self, PagedTableView):
        PagedTableView.setObjectName("PagedTableView")
        PagedTableView.resize(490, 425)
        self.verticalLayout = QtWidgets.QVBoxLayout(PagedTableView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hLayout = QtWidgets.QHBoxLayout()
        self.hLayout.setObjectName("hLayout")
        self.lineEdit = QtWidgets.QLineEdit(PagedTableView)
        self.lineEdit.setText("11")
        self.lineEdit.setObjectName("lineEdit")
        self.hLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(PagedTableView)
        self.label.setObjectName("label")
        self.hLayout.addWidget(self.label)
        self.toolButtonL = QtWidgets.QToolButton(PagedTableView)
        self.toolButtonL.setArrowType(QtCore.Qt.LeftArrow)
        self.toolButtonL.setObjectName("toolButtonL")
        self.hLayout.addWidget(self.toolButtonL)
        self.toolButtonR = QtWidgets.QToolButton(PagedTableView)
        self.toolButtonR.setArrowType(QtCore.Qt.RightArrow)
        self.toolButtonR.setObjectName("toolButtonR")
        self.hLayout.addWidget(self.toolButtonR)
        self.verticalLayout.addLayout(self.hLayout)
        self.tableView = QtWidgets.QTableView(PagedTableView)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(PagedTableView)
        QtCore.QMetaObject.connectSlotsByName(PagedTableView)

    def retranslateUi(self, PagedTableView):
        _translate = QtCore.QCoreApplication.translate
        PagedTableView.setWindowTitle(_translate("PagedTableView", "Form"))
        self.lineEdit.setInputMask(_translate("PagedTableView", "0DD"))
        self.label.setText(_translate("PagedTableView", "1/1"))
        self.toolButtonL.setText(_translate("PagedTableView", "..."))
        self.toolButtonR.setText(_translate("PagedTableView", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PagedTableView = QtWidgets.QWidget()
    ui = Ui_PagedTableView()
    ui.setupUi(PagedTableView)
    PagedTableView.show()
    sys.exit(app.exec_())
