# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fares/Documents/devel/pypointage2/view/testDataTransformation.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestDataTransformation(object):
    def setupUi(self, TestDataTransformation):
        TestDataTransformation.setObjectName("TestDataTransformation")
        TestDataTransformation.resize(414, 300)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(TestDataTransformation)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(TestDataTransformation)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonRun = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonRun.setObjectName("pushButtonRun")
        self.horizontalLayout.addWidget(self.pushButtonRun)
        self.pushButtonRun_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonRun_2.setObjectName("pushButtonRun_2")
        self.horizontalLayout.addWidget(self.pushButtonRun_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView_res = QtWidgets.QTableView(self.verticalLayoutWidget_2)
        self.tableView_res.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_res.setSortingEnabled(True)
        self.tableView_res.setObjectName("tableView_res")
        self.verticalLayout_2.addWidget(self.tableView_res)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(TestDataTransformation)
        QtCore.QMetaObject.connectSlotsByName(TestDataTransformation)

    def retranslateUi(self, TestDataTransformation):
        _translate = QtCore.QCoreApplication.translate
        TestDataTransformation.setWindowTitle(_translate("TestDataTransformation", "Form"))
        self.pushButtonRun.setText(_translate("TestDataTransformation", "Run Transformaion"))
        self.pushButtonRun_2.setText(_translate("TestDataTransformation", "Run Transformaion 2"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("TestDataTransformation", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("TestDataTransformation", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TestDataTransformation", "Test"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("TestDataTransformation", "hello"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("TestDataTransformation", "World"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TestDataTransformation = QtWidgets.QWidget()
    ui = Ui_TestDataTransformation()
    ui.setupUi(TestDataTransformation)
    TestDataTransformation.show()
    sys.exit(app.exec_())
